# services:
#   users-db:
#     image: postgres:17
#     env_file:
#       - .env
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./pgdata:/var/lib/postgresql/data
#       - ./pginit:/docker-entrypoint-initdb.d

#   users-service:
#     build: .
#     env_file:
#       - .env
#     environment:
#       POSTGRES_HOST: "users-db"
#     ports:
#       - "8002:8000"
#     depends_on:
#       - users-db