@UsersService_HostAddress = http://localhost

### Create a user
POST {{UsersService_HostAddress}}/users/
Content-Type: application/json

{
  "name": "julia",
  "email": "julia@example.com"
}

### List all users
GET {{UsersService_HostAddress}}/users/

### Get user by ID
GET {{UsersService_HostAddress}}/users/1

###
